<?php

namespace DFiks\TBank\Payments\Enums;

namespace DFiks\TBank\Payments\Enums;

enum CitizenshipType: int
{
    case Afghanistan = 4;
    case Albania = 8;
    case Antarctica = 10;
    case Algeria = 12;
    case AmericanSamoa = 16;
    case Andorra = 20;
    case Angola = 24;
    case AntiguaAndBarbuda = 28;
    case Azerbaijan = 31;
    case Argentina = 32;
    case Australia = 36;
    case Austria = 40;
    case Bahamas = 44;
    case Bahrain = 48;
    case Bangladesh = 50;
    case Armenia = 51;
    case Barbados = 52;
    case Belgium = 56;
    case Bermuda = 60;
    case Bhutan = 64;
    case Bolivia = 68;
    case BosniaAndHerzegovina = 70;
    case Botswana = 72;
    case BouvetIsland = 74;
    case Brazil = 76;
    case Belize = 84;
    case BritishIndianOceanTerritory = 86;
    case SolomonIslands = 90;
    case BritishVirginIslands = 92;
    case BruneiDarussalam = 96;
    case Bulgaria = 100;
    case Myanmar = 104;
    case Burundi = 108;
    case Belarus = 112;
    case Cambodia = 116;
    case Cameroon = 120;
    case Canada = 124;
    case CaboVerde = 132;
    case CaymanIslands = 136;
    case CentralAfricanRepublic = 140;
    case SriLanka = 144;
    case Chad = 148;
    case Chile = 152;
    case China = 156;
    case Taiwan = 158;
    case ChristmasIsland = 162;
    case CocosIslands = 166;
    case Colombia = 170;
    case Comoros = 174;
    case Mayotte = 175;
    case Congo = 178;
    case DRCongo = 180;
    case CookIslands = 184;
    case CostaRica = 188;
    case Croatia = 191;
    case Cuba = 192;
    case Cyprus = 196;
    case CzechRepublic = 203;
    case Benin = 204;
    case Denmark = 208;
    case Dominica = 212;
    case DominicanRepublic = 214;
    case Ecuador = 218;
    case ElSalvador = 222;
    case EquatorialGuinea = 226;
    case Ethiopia = 231;
    case Eritrea = 232;
    case Estonia = 233;
    case FaroeIslands = 234;
    case FalklandIslands = 238;
    case SouthGeorgia = 239;
    case Fiji = 242;
    case Finland = 246;
    case AlandIslands = 248;
    case France = 250;
    case FrenchGuiana = 254;
    case FrenchPolynesia = 258;
    case FrenchSouthernTerritories = 260;
    case Djibouti = 262;
    case Gabon = 266;
    case Georgia = 268;
    case Gambia = 270;
    case Palestine = 275;
    case Germany = 276;
    case Ghana = 288;
    case Gibraltar = 292;
    case Kiribati = 296;
    case Greece = 300;
    case Greenland = 304;
    case Grenada = 308;
    case Guadeloupe = 312;
    case Guam = 316;
    case Guatemala = 320;
    case Guinea = 324;
    case Guyana = 328;
    case Haiti = 332;
    case HeardIsland = 334;
    case Vatican = 336;
    case Honduras = 340;
    case HongKong = 344;
    case Hungary = 348;
    case Iceland = 352;
    case India = 356;
    case Indonesia = 360;
    case Iran = 364;
    case Iraq = 368;
    case Ireland = 372;
    case Israel = 376;
    case Italy = 380;
    case IvoryCoast = 384;
    case Jamaica = 388;
    case Japan = 392;
    case Kazakhstan = 398;
    case Jordan = 400;
    case Kenya = 404;
    case NorthKorea = 408;
    case SouthKorea = 410;
    case Kuwait = 414;
    case Kyrgyzstan = 417;
    case Laos = 418;
    case Lebanon = 422;
    case Lesotho = 426;
    case Latvia = 428;
    case Liberia = 430;
    case Libya = 434;
    case Liechtenstein = 438;
    case Lithuania = 440;
    case Luxembourg = 442;
    case Macau = 446;
    case Madagascar = 450;
    case Malawi = 454;
    case Malaysia = 458;
    case Maldives = 462;
    case Mali = 466;
    case Malta = 470;
    case Martinique = 474;
    case Mauritania = 478;
    case Mauritius = 480;
    case Mexico = 484;
    case Monaco = 492;
    case Mongolia = 496;
    case Moldova = 498;
    case Montenegro = 499;
    case Montserrat = 500;
    case Morocco = 504;
    case Mozambique = 508;
    case Oman = 512;
    case Namibia = 516;
    case Nauru = 520;
    case Nepal = 524;
    case Netherlands = 528;
    case Curacao = 531;
    case Aruba = 533;
    case SintMaartenDutchPart = 534;
    case Bonaire = 535;
    case NewCaledonia = 540;
    case Vanuatu = 548;
    case NewZealand = 554;
    case Nicaragua = 558;
    case Niger = 562;
    case Nigeria = 566;
    case Niue = 570;
    case NorfolkIsland = 574;
    case Norway = 578;
    case NorthernMarianaIslands = 580;
    case USMinorOutlyingIslands = 581;
    case Micronesia = 583;
    case MarshallIslands = 584;
    case Palau = 585;
    case Pakistan = 586;
    case Panama = 591;
    case PapuaNewGuinea = 598;
    case Paraguay = 600;
    case Peru = 604;
    case Philippines = 608;
    case PitcairnIslands = 612;
    case Poland = 616;
    case Portugal = 620;
    case GuineaBissau = 624;
    case TimorLeste = 626;
    case PuertoRico = 630;
    case Qatar = 634;
    case Reunion = 638;
    case Romania = 642;
    case Russia = 643;
    case Rwanda = 646;
    case SaintBarthelemy = 652;
    case SaintHelena = 654;
    case SaintKittsAndNevis = 659;
    case Anguilla = 660;
    case SaintLucia = 662;
    case SaintMartinFrenchPart = 663;
    case SaintPierreAndMiquelon = 666;
    case SaintVincentAndTheGrenadines = 670;
    case SanMarino = 674;
    case SaoTomeAndPrincipe = 678;
    case SaudiArabia = 682;
    case Senegal = 686;
    case Serbia = 688;
    case Seychelles = 690;
    case SierraLeone = 694;
    case Singapore = 702;
    case Slovakia = 703;
    case Vietnam = 704;
    case Slovenia = 705;
    case Somalia = 706;
    case SouthAfrica = 710;
    case Zimbabwe = 716;
    case Spain = 724;
    case SouthSudan = 728;
    case Sudan = 729;
    case WesternSahara = 732;
    case Suriname = 740;
    case SvalbardAndJanMayen = 744;
    case Eswatini = 748;
    case Sweden = 752;
    case Switzerland = 756;
    case Syria = 760;
    case Tajikistan = 762;
    case Thailand = 764;
    case Togo = 768;
    case Tokelau = 772;
    case Tonga = 776;
    case TrinidadAndTobago = 780;
    case UAE = 784;
    case Tunisia = 788;
    case Turkey = 792;
    case Turkmenistan = 795;
    case TurksAndCaicos = 796;
    case Tuvalu = 798;
    case Uganda = 800;
    case Ukraine = 804;
    case NorthMacedonia = 807;
    case Egypt = 818;
    case UK = 826;
    case Guernsey = 831;
    case Jersey = 832;
    case IsleOfMan = 833;
    case Tanzania = 834;
    case USA = 840;
    case USVirginIslands = 850;
    case BurkinaFaso = 854;
    case Uruguay = 858;
    case Uzbekistan = 860;
    case Venezuela = 862;
    case WallisAndFutuna = 876;
    case Samoa = 882;
    case Yemen = 887;
    case Zambia = 894;
    case Abkhazia = 895;
    case SouthOssetia = 896;
    case Donetsk = 897;
    case Luhansk = 898;

    /**
     * Возвращает буквенный код страны (ISO2).
     */
    public function toIso2(): string
    {
        return match ($this) {
            self::Afghanistan => 'AF',
            self::Albania => 'AL',
            self::Antarctica => 'AQ',
            self::Algeria => 'DZ',
            self::AmericanSamoa => 'AS',
            self::Andorra => 'AD',
            self::Angola => 'AO',
            self::AntiguaAndBarbuda => 'AG',
            self::Azerbaijan => 'AZ',
            self::Argentina => 'AR',
            self::Australia => 'AU',
            self::Austria => 'AT',
            self::Bahamas => 'BS',
            self::Bahrain => 'BH',
            self::Bangladesh => 'BD',
            self::Armenia => 'AM',
            self::Barbados => 'BB',
            self::Belgium => 'BE',
            self::Bermuda => 'BM',
            self::Bhutan => 'BT',
            self::Bolivia => 'BO',
            self::BosniaAndHerzegovina => 'BA',
            self::Botswana => 'BW',
            self::BouvetIsland => 'BV',
            self::Brazil => 'BR',
            self::Belize => 'BZ',
            self::BritishIndianOceanTerritory => 'IO',
            self::SolomonIslands => 'SB',
            self::BritishVirginIslands => 'VG',
            self::BruneiDarussalam => 'BN',
            self::Bulgaria => 'BG',
            self::Myanmar => 'MM',
            self::Burundi => 'BI',
            self::Belarus => 'BY',
            self::Cambodia => 'KH',
            self::Cameroon => 'CM',
            self::Canada => 'CA',
            self::CaboVerde => 'CV',
            self::CaymanIslands => 'KY',
            self::CentralAfricanRepublic => 'CF',
            self::SriLanka => 'LK',
            self::Chad => 'TD',
            self::Chile => 'CL',
            self::China => 'CN',
            self::Taiwan => 'TW',
            self::ChristmasIsland => 'CX',
            self::CocosIslands => 'CC',
            self::Colombia => 'CO',
            self::Comoros => 'KM',
            self::Mayotte => 'YT',
            self::Congo => 'CG',
            self::DRCongo => 'CD',
            self::CookIslands => 'CK',
            self::CostaRica => 'CR',
            self::Croatia => 'HR',
            self::Cuba => 'CU',
            self::Cyprus => 'CY',
            self::CzechRepublic => 'CZ',
            self::Benin => 'BJ',
            self::Denmark => 'DK',
            self::Dominica => 'DM',
            self::DominicanRepublic => 'DO',
            self::Ecuador => 'EC',
            self::ElSalvador => 'SV',
            self::EquatorialGuinea => 'GQ',
            self::Ethiopia => 'ET',
            self::Eritrea => 'ER',
            self::Estonia => 'EE',
            self::FaroeIslands => 'FO',
            self::FalklandIslands => 'FK',
            self::SouthGeorgia => 'GS',
            self::Fiji => 'FJ',
            self::Finland => 'FI',
            self::AlandIslands => 'AX',
            self::France => 'FR',
            self::FrenchGuiana => 'GF',
            self::FrenchPolynesia => 'PF',
            self::FrenchSouthernTerritories => 'TF',
            self::Djibouti => 'DJ',
            self::Gabon => 'GA',
            self::Georgia => 'GE',
            self::Gambia => 'GM',
            self::Palestine => 'PS',
            self::Germany => 'DE',
            self::Ghana => 'GH',
            self::Gibraltar => 'GI',
            self::Kiribati => 'KI',
            self::Greece => 'GR',
            self::Greenland => 'GL',
            self::Grenada => 'GD',
            self::Guadeloupe => 'GP',
            self::Guam => 'GU',
            self::Guatemala => 'GT',
            self::Guinea => 'GN',
            self::Guyana => 'GY',
            self::Haiti => 'HT',
            self::HeardIsland => 'HM',
            self::Vatican => 'VA',
            self::Honduras => 'HN',
            self::HongKong => 'HK',
            self::Hungary => 'HU',
            self::Iceland => 'IS',
            self::India => 'IN',
            self::Indonesia => 'ID',
            self::Iran => 'IR',
            self::Iraq => 'IQ',
            self::Ireland => 'IE',
            self::Israel => 'IL',
            self::Italy => 'IT',
            self::IvoryCoast => 'CI',
            self::Jamaica => 'JM',
            self::Japan => 'JP',
            self::Kazakhstan => 'KZ',
            self::Jordan => 'JO',
            self::Kenya => 'KE',
            self::NorthKorea => 'KP',
            self::SouthKorea => 'KR',
            self::Kuwait => 'KW',
            self::Kyrgyzstan => 'KG',
            self::Laos => 'LA',
            self::Lebanon => 'LB',
            self::Lesotho => 'LS',
            self::Latvia => 'LV',
            self::Liberia => 'LR',
            self::Libya => 'LY',
            self::Liechtenstein => 'LI',
            self::Lithuania => 'LT',
            self::Luxembourg => 'LU',
            self::Macau => 'MO',
            self::Madagascar => 'MG',
            self::Malawi => 'MW',
            self::Malaysia => 'MY',
            self::Maldives => 'MV',
            self::Mali => 'ML',
            self::Malta => 'MT',
            self::Martinique => 'MQ',
            self::Mauritania => 'MR',
            self::Mauritius => 'MU',
            self::Mexico => 'MX',
            self::Monaco => 'MC',
            self::Mongolia => 'MN',
            self::Moldova => 'MD',
            self::Montenegro => 'ME',
            self::Montserrat => 'MS',
            self::Morocco => 'MA',
            self::Mozambique => 'MZ',
            self::Oman => 'OM',
            self::Namibia => 'NA',
            self::Nauru => 'NR',
            self::Nepal => 'NP',
            self::Netherlands => 'NL',
            self::Curacao => 'CW',
            self::Aruba => 'AW',
            self::SintMaartenDutchPart => 'SX',
            self::Bonaire => 'BQ',
            self::NewCaledonia => 'NC',
            self::Vanuatu => 'VU',
            self::NewZealand => 'NZ',
            self::Nicaragua => 'NI',
            self::Niger => 'NE',
            self::Nigeria => 'NG',
            self::Niue => 'NU',
            self::NorfolkIsland => 'NF',
            self::Norway => 'NO',
            self::NorthernMarianaIslands => 'MP',
            self::USMinorOutlyingIslands => 'UM',
            self::Micronesia => 'FM',
            self::MarshallIslands => 'MH',
            self::Palau => 'PW',
            self::Pakistan => 'PK',
            self::Panama => 'PA',
            self::PapuaNewGuinea => 'PG',
            self::Paraguay => 'PY',
            self::Peru => 'PE',
            self::Philippines => 'PH',
            self::PitcairnIslands => 'PN',
            self::Poland => 'PL',
            self::Portugal => 'PT',
            self::GuineaBissau => 'GW',
            self::TimorLeste => 'TL',
            self::PuertoRico => 'PR',
            self::Qatar => 'QA',
            self::Reunion => 'RE',
            self::Romania => 'RO',
            self::Russia => 'RU',
            self::Rwanda => 'RW',
            self::SaintBarthelemy => 'BL',
            self::SaintHelena => 'SH',
            self::SaintKittsAndNevis => 'KN',
            self::Anguilla => 'AI',
            self::SaintLucia => 'LC',
            self::SaintMartinFrenchPart => 'MF',
            self::SaintPierreAndMiquelon => 'PM',
            self::SaintVincentAndTheGrenadines => 'VC',
            self::SanMarino => 'SM',
            self::SaoTomeAndPrincipe => 'ST',
            self::SaudiArabia => 'SA',
            self::Senegal => 'SN',
            self::Serbia => 'RS',
            self::Seychelles => 'SC',
            self::SierraLeone => 'SL',
            self::Singapore => 'SG',
            self::Slovakia => 'SK',
            self::Vietnam => 'VN',
            self::Slovenia => 'SI',
            self::Somalia => 'SO',
            self::SouthAfrica => 'ZA',
            self::Zimbabwe => 'ZW',
            self::Spain => 'ES',
            self::SouthSudan => 'SS',
            self::Sudan => 'SD',
            self::WesternSahara => 'EH',
            self::Suriname => 'SR',
            self::SvalbardAndJanMayen => 'SJ',
            self::Eswatini => 'SZ',
            self::Sweden => 'SE',
            self::Switzerland => 'CH',
            self::Syria => 'SY',
            self::Tajikistan => 'TJ',
            self::Thailand => 'TH',
            self::Togo => 'TG',
            self::Tokelau => 'TK',
            self::Tonga => 'TO',
            self::TrinidadAndTobago => 'TT',
            self::UAE => 'AE',
            self::Tunisia => 'TN',
            self::Turkey => 'TR',
            self::Turkmenistan => 'TM',
            self::Tuvalu => 'TV',
            self::Uganda => 'UG',
            self::Ukraine => 'UA',
            self::NorthMacedonia => 'MK',
            self::Egypt => 'EG',
            self::UK => 'GB',
            self::Guernsey => 'GG',
            self::Jersey => 'JE',
            self::IsleOfMan => 'IM',
            self::Tanzania => 'TZ',
            self::USA => 'US',
            self::USVirginIslands => 'VI',
            self::BurkinaFaso => 'BF',
            self::Uruguay => 'UY',
            self::Uzbekistan => 'UZ',
            self::Venezuela => 'VE',
            self::WallisAndFutuna => 'WF',
            self::Samoa => 'WS',
            self::Yemen => 'YE',
            self::Zambia => 'ZM',
            self::Abkhazia => 'AB',
            self::SouthOssetia => 'OS',
            self::Donetsk => 'DN',
            self::Luhansk => 'LN',
        };
    }
}
